# Generated by Django 5.2.16 on 2026-07-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuvePrincipale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('capacite', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuve principale',
                'verbose_name_plural': 'Cuves principales',
                'db_table': 'cuve_principale',
                'ordering': ['identifiant'],
            },
        ),
        migrations.CreateModel(
            name='GroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('puissance', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe électrogène',
                'verbose_name_plural': 'Groupes électrogènes',
                'db_table': 'groupe_electrogene',
                'ordering': ['identifiant'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('localisation', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CuveJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('capacite', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuve_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_journalieres', to='sites.cuveprincipale')),
                ('groupe_electrogene', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuve_journaliere', to='sites.groupeelectrogene')),
            ],
            options={
                'verbose_name': 'Cuve journalière',
                'verbose_name_plural': 'Cuves journalières',
                'db_table': 'cuve_journaliere',
                'ordering': ['identifiant'],
            },
        ),
        migrations.AddField(
            model_name='cuveprincipale',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves_principales', to='sites.site'),
        ),
    ]
