# Generated by Django 5.2.16 on 2026-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom unique du site (ex: Site Douala Nord)', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code technique du site', max_length=50, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, help_text='Adresse physique du site', null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
                'ordering': ['nom'],
            },
        ),
    ]
