# Generated by Django 5.2.16 on 2026-07-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='site',
        ),
        migrations.RemoveField(
            model_name='cuveprincipale',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['date_debut', 'id'], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='RapportSoumission',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
