# Generated by Django 5.2.16 on 2026-07-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_cuveprincipale_identifiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='groupe_electrogene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuve_journaliere', to='sites.groupeelectrogene'),
        ),
    ]
