# Generated by Django 5.2.16 on 2026-07-29 14:11

import apps.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_cuvejournaliere_groupe_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuvejournaliere',
            name='identifiant',
            field=models.CharField(help_text='Format CJxxx (ex. CJ001)', max_length=100, unique=True, validators=[apps.sites.models.validate_cj_identifiant]),
        ),
    ]
