# Generated by Django 5.2.16 on 2026-08-06 03:19
#
# Transfert d’état vers apps.equipment : les tables physiques restent
# (mêmes db_table). Un DeleteModel réel les dropperait au premier migrate Docker.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alerte_cuve_journaliere_and_more'),
        ('equipment', '0001_initial'),
        ('reports', '0002_alter_lignerapport_cuve_journaliere_and_more'),
        ('sites', '0004_cuvejournaliere_cjxxx'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='cuveprincipale',
                    name='site',
                ),
                migrations.DeleteModel(
                    name='CuveJournaliere',
                ),
                migrations.DeleteModel(
                    name='GroupeElectrogene',
                ),
                migrations.DeleteModel(
                    name='CuvePrincipale',
                ),
            ],
            database_operations=[],
        ),
    ]
