# Generated by Django 5.2.16 on 2026-09-01 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('reports', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(blank=True, db_index=True, help_text='Clé unique anti-doublon (ex: groupe-3-autonomie_critique)', max_length=120, null=True, unique=True)),
                ('date_apparition', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], db_index=True, default='moyenne', max_length=20)),
                ('type_alerte', models.CharField(choices=[('autonomie_critique', 'Autonomie critique (< 24h)'), ('conso_sans_horaire', 'Consommation sans delta horaire'), ('horaire_sans_conso', 'Delta horaire sans consommation'), ('ecart_conso', 'Écart de consommation (> 15%)')], db_index=True, default='ecart_conso', max_length=50)),
                ('message', models.TextField(help_text='Message explicatif affiché dans le dashboard')),
                ('donnees_contexte', models.JSONField(blank=True, default=dict, help_text='Données ayant déclenché l’alerte (autonomie, écart, ids…)')),
                ('etat', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], db_index=True, default='nouvelle', max_length=20)),
                ('justification', models.TextField(blank=True, default='')),
                ('cuve_journaliere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipment.cuvejournaliere')),
                ('groupe_electrogene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipment.groupeelectrogene')),
                ('ligne_rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='reports.lignerapport')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='sites.site')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
                'ordering': ['-date_apparition', '-id'],
                'indexes': [models.Index(fields=['etat', 'priorite'], name='alerte_etat_2e88c1_idx'), models.Index(fields=['site', 'etat'], name='alerte_site_id_a86da3_idx'), models.Index(fields=['type_alerte', 'date_apparition'], name='alerte_type_al_a823ed_idx')],
            },
        ),
    ]
