# Generated by Django 5.2.16 on 2026-07-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_apparition', models.DateField(auto_now_add=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('type_alerte', models.CharField(choices=[('seuil_bas', 'Seuil bas'), ('panne', 'Panne'), ('ecart_releve', 'Écart de relevé'), ('compteur_anormal', 'Compteur anormal'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('message', models.TextField()),
                ('etat', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], default='nouvelle', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('cuve_journaliere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='sites.cuvejournaliere')),
                ('groupe_electrogene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='sites.groupeelectrogene')),
                ('ligne_rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='reports.lignerapport')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='sites.site')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
                'ordering': ['-date_apparition'],
            },
        ),
    ]
