# Generated by Django 5.2.16 on 2026-07-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='cle',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
