# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='date_detection',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='Instant réel de détection (dépôt de fiche) — date + heure affichées dans l’UI.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(
                choices=[
                    ('autonomie_critique', 'Autonomie inférieure à 24 h'),
                    ('autonomie_preventive', 'Autonomie inférieure à 36 h'),
                    ('conso_sans_fonctionnement', 'Consommation sans fonctionnement'),
                    ('fonctionnement_sans_consommation', 'Fonctionnement sans consommation'),
                    ('ecart_conso', 'Écart de consommation horaire')
                ],
                db_index=True,
                default='ecart_conso',
                max_length=50,
            ),
        ),
    ]