# Generated by Django 5.2.16 on 2026-07-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alerte_metier_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerte',
            options={'ordering': ['-date_apparition', '-id'], 'verbose_name': 'Alerte', 'verbose_name_plural': 'Alertes'},
        ),
        migrations.RenameIndex(
            model_name='alerte',
            new_name='alerte_etat_2e88c1_idx',
            old_name='alerte_etat_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='alerte',
            new_name='alerte_site_id_a86da3_idx',
            old_name='alerte_site_etat_idx',
        ),
        migrations.RenameIndex(
            model_name='alerte',
            new_name='alerte_type_al_a823ed_idx',
            old_name='alerte_type_date_idx',
        ),
    ]
