# Generated by Django 5.2.16 on 2026-08-06 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alerte_options_and_more'),
        ('equipment', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='cuve_journaliere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipment.cuvejournaliere'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='date_apparition',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='groupe_electrogene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipment.groupeelectrogene'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('autonomie_critique', 'Autonomie critique (< 24h)'), ('conso_sans_horaire', 'Consommation sans delta horaire'), ('horaire_sans_conso', 'Delta horaire sans consommation'), ('ecart_conso', 'Écart de consommation (> 15%)')], db_index=True, default='ecart_conso', max_length=50),
        ),
    ]
