# Generated by Django 5.2.16 on 2026-07-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userprofile_three_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['date_debut', 'date_fin', 'id'], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
    ]
