# Generated by Django 5.2.16 on 2026-07-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('sites', '0002_alter_cuveprincipale_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='sites.site', verbose_name='Site rattaché'),
        ),
    ]
