# Generated by Django 5.2.16 on 2026-08-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilutilisateur_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='site',
        ),
    ]
