# Generated by Django 5.2.16 on 2026-07-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapport',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_gasoil_cuve_principale', models.FloatField(blank=True, null=True)),
                ('quantite_gasoil_cuve_journaliere', models.FloatField(blank=True, null=True)),
                ('compteur_horaire', models.FloatField(blank=True, null=True)),
                ('depotage', models.FloatField(blank=True, null=True)),
                ('etat_fonctionnement', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('cuve_journaliere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='sites.cuvejournaliere')),
                ('cuve_principale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='sites.cuveprincipale')),
                ('groupe_electrogene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='sites.groupeelectrogene')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reports.rapport')),
            ],
            options={
                'verbose_name': 'Ligne de rapport',
                'verbose_name_plural': 'Lignes de rapport',
                'db_table': 'ligne_rapport',
            },
        ),
    ]
