# Generated by Django 5.2.16 on 2026-08-06 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignerapport',
            name='cuve_journaliere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='equipment.cuvejournaliere'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='cuve_principale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='equipment.cuveprincipale'),
        ),
        migrations.AlterField(
            model_name='lignerapport',
            name='groupe_electrogene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_rapport', to='equipment.groupeelectrogene'),
        ),
    ]
